# Generated by Django 4.0.5 on 2022-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=20)),
                ('interest', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resume/pdfs')),
            ],
        ),
    ]
