# Generated by Django 4.0.5 on 2022-06-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selectedResume',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_email', models.EmailField(max_length=30)),
                ('candidate_phone', models.CharField(max_length=10)),
                ('candidate_experience', models.CharField(max_length=20)),
                ('candidate_interest', models.CharField(max_length=50)),
                ('candidate_resume', models.FileField(upload_to='recruiter/pdfs')),
            ],
        ),
    ]
